version: "3.9"

services:
  database:
    image: postgres
    container_name: database_loan
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/data/postgres
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  # app:
  #   build: .
  #   container_name: loan
  #   ports:
  #     - 3333:3333
  #     - 9229:9229
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database
  #   depends_on:
  #     - database

volumes:
  pgdata:
    driver: local